apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-client
  template:
    metadata:
      labels:
        app: mqtt-client
    spec:
      containers:
        - name: mqtt-client
          image: mqtt_client:latest_local
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: "Host=host.docker.internal;Port=5432;Database=ENSURE;Username=postgres;Password=password;"
            - name: MQTT
              value: "mqtt-broker"
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-client
spec:
  selector:
    app: mqtt-client
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883